language: ruby
rvm:
- 2.6.4
deploy:
  api_key:
    secure: CTD1S77AwUu2Q3sSn0tek0JPgwbFt44yjOGGrxtSvyr8fnz4WwNzarZMzqITJM0mdNWB5CONgfHMOFbMmxYQYSwYbaYoTxO66ZbKzVhAJOTW5mf0Eb6wfXzNF95JnfQhSILqre5s7pDNYTNIrbduzyPYGtVZxbD7IXSetTHUyifWOLYveQQLTNBwmwYRhCN1tw+6Z96mjw0Rn0iCxwjWRIV+98InXJdawHZVoFOhx8C6UBwGX3/8ec7q2AvhIbQjHg8vNCP5afRTnGAdboOGVnv9YHjxaZxB5p5Z8FYjNEAdYlAL1TimBY9HG4edyoqlGFoX0sle8Q0Er+Zkdz+FpMyHSW3iz1Cg93KNMjUQmgJtw0x+oqnGfY5Hd4gC5KS/mbTEDdVQku8r2e9PwuCZWdUxdcOdUOIeuKUvFcr/kYvs2EtdWC05GxM0ucRDdoZkRQePFhwe83HmOFnCEbCksgyTYMb5CXpVPxrIdNPR+phLyuG7KvEml227+CriJfd0m1+ZnqG0xZLaRzw6Mn2egOoRS1vzSBfXVt6OhdCAiXAT5ZnYmdS703OnZHKNhnsNl0vm+4XYLaz8YNuAMhyoWeYpq0avWhyt+j8T/Pc8x7qhwbESD1USkPQehrpTcSAxO7S+pP67oNvl2aLTdXTw7CwcRmulWtyCkkDuDVvEo1k=
